# Generated by cpp11: do not edit by hand

GetDivisorsC <- function(Rv, RNamed, RShowStats, RSkipExtPR, RSkipECM, RNumThreads, maxThreads) {
  .Call(`_RcppBigIntAlgos_GetDivisorsC`, Rv, RNamed, RShowStats, RSkipExtPR, RSkipECM, RNumThreads, maxThreads)
}

cpp11GetNumThreads <- function() {
  .Call(`_RcppBigIntAlgos_cpp11GetNumThreads`)
}

PrimeFactorization <- function(Rv, RNamed, RShowStats, RSkipExtPR, RSkipECM, RNumThreads, maxThreads) {
  .Call(`_RcppBigIntAlgos_PrimeFactorization`, Rv, RNamed, RShowStats, RSkipExtPR, RSkipECM, RNumThreads, maxThreads)
}
