# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetDivisorsC <- function(Rv, RNamed, RShowStats, RSkipExtPR, RSkipECM, RNumThreads, maxThreads) {
    .Call(`_RcppBigIntAlgos_GetDivisorsC`, Rv, RNamed, RShowStats, RSkipExtPR, RSkipECM, RNumThreads, maxThreads)
}

cpp11GetNumThreads <- function() {
    .Call(`_RcppBigIntAlgos_cpp11GetNumThreads`)
}

PrimeFactorization <- function(Rv, RNamed, RShowStats, RSkipExtPR, RSkipECM, RNumThreads, maxThreads) {
    .Call(`_RcppBigIntAlgos_PrimeFactorization`, Rv, RNamed, RShowStats, RSkipExtPR, RSkipECM, RNumThreads, maxThreads)
}

