# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetDivisorsC <- function(Rv, RNamed, RNumThreads, maxThreads) {
    .Call(`_RcppBigIntAlgos_GetDivisorsC`, Rv, RNamed, RNumThreads, maxThreads)
}

cpp11GetNumThreads <- function() {
    .Call(`_RcppBigIntAlgos_cpp11GetNumThreads`)
}

QuadraticSieveContainer <- function(Rn, RShowStats, RNumThreads, maxThreads) {
    .Call(`_RcppBigIntAlgos_QuadraticSieveContainer`, Rn, RShowStats, RNumThreads, maxThreads)
}

